name: Notify parent repo

on:
  push:
    branches: [main]  # 혹은 사용하는 브랜치

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify personal-lab
        run: |
          curl -X POST https://api.github.com/repos/ckaanf/personal-lab/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.PARENT_REPO_PAT }}" \
          -d '{"event_type":"submodule-updated"}'
